<?php
require_once("../model/User.php");
require_once("../model/RP.php");
$ac=new AC;
$ac->setId(1);
$ac->setLogin("pabass");
$ac->setPassword("bass");
echo $ac->getRole("br");
echo $ac->getLogin();
$etudiant=new Etudiant;
$etudiant->setNomComplet("bass ndiaye");
$etudiant->setId("13569739");
$etudiant->setTuteur("Pere: laye");
$etudiant->setLogin("Pabass");
$etudiant->setPassword("password123");
echo $etudiant->getId();
echo $etudiant->getNomComplet();
echo $etudiant->getLogin();
echo $etudiant->getRole();
echo $etudiant->getTuteur();
